# -*- coding: utf-8 -*-
"""Damos-lhe as boas-vindas ao Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Lendo texto (sempre retorna string)
nome = input("Digite seu nome: ")

# Lendo número inteiro
idade = int(input("Digite sua idade: "))

# Lendo número real
cidade = (input("Digite sua cidade: "))

print(f"Olá {nome}, você tem {idade} anos e mora em {cidade}.")