# -*- coding: utf-8 -*-
"""Damos-lhe as boas-vindas ao Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

numero = int  (input("digite um numero inteiro") )

dobro = numero * 2

metade = numero /2
print(f"numero digitado: {numero} " )
print(f"dobro: {dobro}")
print(f"metade: {metade}")