# -*- coding: utf-8 -*-
"""Damos-lhe as boas-vindas ao Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# @title Texto de título predefinido
# Criando strings
nome = input("Digite seu nome completo: ")

# Acessando por índice (começa em 0)
print(f"Primeira letra: {nome[0]}")
print(f"Última letra: {nome[-1]}")

nome = input("digite seu nome: ")
nome_maiusculo = nome.upper( )
print(nome_maiusculo)

# Tamanho da string
print(f"O nome {nome} tem {len(nome)} caracteres")